### ISSUE TITLE
TypeError: Cannot read property 'unMeta' of undefined

### ISSUE THREAD

**Issue by truenicoco** [mvhenderson/pandoc-docx-title#1]
I would really like to use your pandoc filter. Unfortunately I don't much about javascript or node. I've successfully installed `pandoc-filter` and `lodash` with `npm`, but apparently it is not enough.

Here's the full output of my document "compilation"

```
$ make
pandoc --standalone \
	--bibliography=src/main.bib \
	--filter pandoc-citeproc --csl include/circulation.csl \
	--filter include/docx-title.js \
	-o build/main.docx \
	src/main.md
/home/ncedilni/doc/publis/circulation2017/include/docx-title.js:24
    var meta = pandoc[0].unMeta;
                        ^

TypeError: Cannot read property 'unMeta' of undefined
    at Socket.<anonymous> (/home/ncedilni/doc/publis/circulation2017/include/docx-title.js:24:25)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
pandoc: Error running filter include/docx-title.js
Filter returned error status 1
make: *** [Makefile:10: all] Error 83
```

For information:
```
$ pandoc -v
pandoc 1.19.1
Compiled with pandoc-types 1.17.0.5, texmath 0.9.1, highlighting-kate 0.6.4
```

**Comment by mvhenderson** [comment]
@truenicoco This is fixed now. However note if your input markdown had an `abstract` item you will need to rename it to `abstr` to avoid getting two abstracts. Apparently pandoc added support for abstract since the last time I touched this project.
